import type { AnalysisRecord } from '@veritas/shared'

const VERDICT_LABELS: Record<string, string> = {
  credible: 'Credible',
  mixed: 'Mixed',
  misleading: 'Misleading',
  unsupported: 'Unsupported',
}

const CLAIM_LABELS: Record<string, string> = {
  verified: 'Verified',
  disputed: 'Disputed',
  unverified: 'Unverified',
  false: 'False',
}

function heading(text: string, level = 2): string {
  return `${'#'.repeat(level)} ${text}\n\n`
}

export function generateReportMarkdown(record: AnalysisRecord): string {
  const { report } = record
  const title = record.title ?? 'Untitled analysis'
  const date = new Date(record.createdAt).toLocaleString()
  const lines: string[] = []

  lines.push('# Veritas AI — Credibility Report\n')
  lines.push(`**${title}**\n`)
  lines.push(`*${record.sourceType} · ${date}*\n`)

  if (record.category) {
    lines.push(`**Category:** ${record.category}\n`)
  }

  lines.push('---\n')
  lines.push(`## Trust Score: ${report.trustScore} / 100\n`)
  lines.push(
    `**Verdict:** ${VERDICT_LABELS[report.verdict] ?? report.verdict}\n`,
  )

  lines.push(heading('Summary'))
  lines.push(`${report.summary}\n`)

  lines.push(heading("Explain Like I'm 15"))
  lines.push(`${report.eli15}\n`)

  lines.push(heading('Neutral Rewrite'))
  lines.push(`${report.neutralRewrite}\n`)

  if (report.claims.length > 0) {
    lines.push(heading('Claims'))
    for (const claim of report.claims) {
      lines.push(
        `### ${claim.claim}\n`,
        `- **Status:** ${CLAIM_LABELS[claim.status] ?? claim.status}`,
        `- **Confidence:** ${claim.confidence}%`,
        `- **Explanation:** ${claim.explanation}`,
      )
      if (claim.evidence.length > 0) {
        lines.push('- **Evidence:**')
        for (const item of claim.evidence) {
          lines.push(`  - ${item}`)
        }
      }
      lines.push('')
    }
  }

  lines.push(heading('Bias Analysis'))
  lines.push(
    `Overall: ${report.bias.overall}% · Political: ${report.bias.political}% · Commercial: ${report.bias.commercial}% · Ideological: ${report.bias.ideological}%\n`,
  )
  lines.push(`${report.bias.explanation}\n`)

  lines.push(heading('Emotional Manipulation'))
  lines.push(
    `Fear: ${report.emotion.fear}% · Urgency: ${report.emotion.urgency}% · Anger: ${report.emotion.anger}% · Sensationalism: ${report.emotion.sensationalism}% · Loaded language: ${report.emotion.loadedLanguage}%\n`,
  )
  lines.push(`Dominant tone: ${report.emotion.dominant}\n`)

  if (report.fallacies.length > 0) {
    lines.push(heading('Logical Fallacies'))
    for (const fallacy of report.fallacies) {
      lines.push(`- **${fallacy.type}** — "${fallacy.excerpt}"`)
      lines.push(`  ${fallacy.explanation}\n`)
    }
  }

  if (report.missingContext.length > 0) {
    lines.push(heading('Missing Context'))
    for (const item of report.missingContext) {
      lines.push(`- ${item}`)
    }
    lines.push('')
  }

  if (report.suggestedReading.length > 0) {
    lines.push(heading('Suggested Reading'))
    for (const source of report.suggestedReading) {
      const link = source.url ? ` ([link](${source.url}))` : ''
      lines.push(`- **${source.title}**${link} — ${source.reason}`)
    }
    lines.push('')
  }

  if (report.reasoningTimeline.length > 0) {
    lines.push(heading('Reasoning Timeline'))
    for (const step of report.reasoningTimeline) {
      lines.push(`1. **${step.step}** — ${step.description}`)
    }
    lines.push('')
  }

  lines.push('---\n')
  lines.push('*Generated by Veritas AI*\n')

  return lines.join('\n')
}
