import PDFDocument from 'pdfkit'
import type { AnalysisRecord } from '@veritas/shared'

const VERDICT_LABELS: Record<string, string> = {
  credible: 'Credible',
  mixed: 'Mixed',
  misleading: 'Misleading',
  unsupported: 'Unsupported',
}

const CLAIM_LABELS: Record<string, string> = {
  verified: 'Verified',
  disputed: 'Disputed',
  unverified: 'Unverified',
  false: 'False',
}

function writeSection(doc: InstanceType<typeof PDFDocument>, title: string, body: string) {
  doc.moveDown(0.5).fontSize(12).fillColor('#0a0a0a').text(title, { underline: true })
  doc.moveDown(0.25).fontSize(10).fillColor('#333333').text(body, { align: 'left' })
}

export function generateReportPdf(record: AnalysisRecord): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' })
    const chunks: Buffer[] = []

    doc.on('data', (chunk: Buffer) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    const { report } = record
    const title = record.title ?? 'Untitled analysis'
    const date = new Date(record.createdAt).toLocaleString()

    doc.fontSize(20).fillColor('#0a0a0a').text('Veritas AI', { align: 'left' })
    doc.fontSize(10).fillColor('#666666').text('Credibility Report')
    doc.moveDown(0.5)
    doc.fontSize(16).fillColor('#0a0a0a').text(title)
    doc.fontSize(9).fillColor('#666666').text(`${record.sourceType} · ${date}`)

    doc.moveDown(1)
    doc.fontSize(28).fillColor('#d4af37').text(`${report.trustScore}`, { continued: true })
    doc.fontSize(14).fillColor('#0a0a0a').text(' / 100 Trust Score')
    doc.fontSize(12).fillColor('#0a0a0a').text(
      `Verdict: ${VERDICT_LABELS[report.verdict] ?? report.verdict}`,
    )

    writeSection(doc, 'Summary', report.summary)
    writeSection(doc, "Explain Like I'm 15", report.eli15)

    if (report.claims.length > 0) {
      doc.moveDown(0.5).fontSize(12).fillColor('#0a0a0a').text('Claims', { underline: true })
      report.claims.forEach((claim, index) => {
        doc
          .moveDown(0.25)
          .fontSize(10)
          .fillColor('#333333')
          .text(
            `${index + 1}. [${CLAIM_LABELS[claim.status] ?? claim.status}] ${claim.claim} (${claim.confidence}% confidence)`,
          )
        if (claim.explanation) {
          doc.fontSize(9).fillColor('#666666').text(claim.explanation, { indent: 12 })
        }
      })
    }

    writeSection(
      doc,
      'Bias Analysis',
      `Overall: ${report.bias.overall}/100 — ${report.bias.explanation}`,
    )

    if (report.fallacies.length > 0) {
      doc.moveDown(0.5).fontSize(12).fillColor('#0a0a0a').text('Fallacies', { underline: true })
      report.fallacies.forEach((fallacy) => {
        doc
          .moveDown(0.25)
          .fontSize(10)
          .fillColor('#333333')
          .text(`${fallacy.type}: "${fallacy.excerpt}" — ${fallacy.explanation}`)
      })
    }

    if (report.missingContext.length > 0) {
      writeSection(doc, 'Missing Context', report.missingContext.join('\n• '))
    }

    writeSection(doc, 'Neutral Rewrite', report.neutralRewrite)

    doc.moveDown(2).fontSize(8).fillColor('#999999').text(
      'Generated by Veritas AI — Don\'t consume information. Verify it.',
      { align: 'center' },
    )

    doc.end()
  })
}
